== Challenge Register

Jedes Teammitglied kann ein Challenge erzeugen.

Es gibt 3 Arten von Challenges:

. Änderungsantrag/ request for Change Ein Vorschlag zur Änderung einer
Baseline. z.B Der Benutzervertreter möchte die Kapazität eines Produkts
von 100 auf 150 Anwender erhöhen. -> ist immer mit den Stakeholdern
abzustimmen und zu dokumentieren.
. Spezifikationsabweichung / off-specification Ein im Rahmen des
projekts zu erfüllende Anforderung, die derzeit nicht (bzw.
voraussichtlich nicht) erfüllt wird. z.B. Mitteilung eines Lieferanten,
dass er ein Produkt nicht liefern kann.
. Problem/Bedenken Sonstiges Issue, dessen Lösung oder Eskalation
Aufgabe des Projekmanagements ist. z.B. Mitteilung eines Teammitglieds,
dass Erkrankung vorliegt und Fertigstellung verzögert wird.

Nachdem ein Issue erkannt und erfasst wurde, muss in einem
kontrollierten Prozess bewertet und entschieden werden, wie darauf
reagiert wird.

Isuses sind: Änderungen in Roles and Responsibilities, New Risks,
Änderungen der Produktvision und RoadMaps.

[cols=",,,,,,,,",options="header",]
|===
|Beschreibung |Identifikation |Wirkung auf |Dringlichkeit/Schweregrad
|aufgetreten am |erstellt durch |Reaktion |Verantwortlicher |Abschluss
am
|Prpgrammiersprache unbekannt |Problem |Team |dringend |30.4.23 |Hans
Mustermann |Schulung geplant |Helga Musterfrau |offen

|Änderung der API |Spezifikationsabweichung |Produkt |mittel |27.4.23
|hans Mustermann |Ticket erstellt |Hans Mustermann |28.4.23

|Responsibility geändert zu Verantworlich für Website
|Spezifikationsabweichung |Team |leicht |25.4.23 |Helga Musterfrau
|Roles/Responsibilieties geändert |Helge Musterfrau |27.4.23

| | | | | | | | |
|===
