== Problemdefinition

=== Hintergrund
Die *Grundig Business GmbH & Co. KG* (gbs) hat eine Software namens *GoSpeech* geschaffen mit der Audiodateien transkribiert werden können. Die Software nutzt dafür *KI*, die jedoch je nach Audioqualität Fehler macht. Das Korrigieren von Audio-Untertiteln ist heute ein gelöstes Problem und kann durch frei verfügbare Software durchgeführt werden. In einem Live-Kontext jedoch fehlen aktuell Wege um falsch generierte Untertitel auszutauschen.

=== Ziel
Die von unseren Entwicklern entwickelte Software, möchte eine Software schaffen die das Korrigieren von Live-Untertitelung, so einfach wie möglich macht. *GoSpeech* wird uns zusammen mit dem Video/Audio auch die automatisch generierten Untertitel mitliefern, sodass von unsrer Software aus diese kontrolliert, korrigiert, und an den Endkunden ausgeliefert werden kann.

=== Herausforderungen
Die offensichtlichste Herausforderung wird sein einen guten Prozessfluss zu entwickeln dem es dem Nutzer ermöglicht zu lesen, Fehler zu identifizieren und zu korrigieren. Dabei darf er nicht aus dem vorher festgelegten Timeframe fallen, wenn er nicht schnell genug die Fehler korrigiert bekommt. 
Da wir als Quelledaten das Video und die Audio getrennt von den Untertiteln erhalten, ist es ebenfalls eine Herausforderung, die einzelnen Wörter zu gut proportioniert Untertitelblöcken zusammen zu bauen.

=== Anforderungen
Unser Kunde arbeitet bei sich intern mit *ASP.NET* und *Angular*, und wünscht dass diese Technologien von uns verwendet werden, da es die Integration in Ihre Systeme erleichtert. Dies steigert zudem die Wartbarkeit und erleichtert die Problemlösungsfindung, da der Kunde mit diesem Techstack bereits Erfahrung hat.
Eine weitere Anforderung ist das die Software *DSGVO*-konform sein muss, damit diese in Deutschland (oder der EU) betrieben werden darf.

=== Zielgruppe
Die Software hat keine spezielle Zielgruppe. Jeder *Leihe* soll in der Lage sein die Software bedienen zu können. Da jedoch das Aufgabenfeld der Software in den Bereich der *Stenografie* hineinragt, soll sie ein paar Komfortfeatures für diese Gruppe bieten. In erster Linie bezieht sich dies auf die Verwendbarkeit von Stenografie-Equipment, wie Fußschalter und besondere Zusatztastaturen.
