:imagesdir: ./img
<<<

== Kontextabgrenzung

Dieser Abschnitt beschreibt das Umfeld von Subletic. Für welche Benutzer ist es da, und mit welchen Fremdsystemen interagiert es?

=== Fachlicher Kontext

image::FachlicherKontext.drawio.svg[Static,80%,align="center"]

==== Stenograph (Benutzer)

Das Korrigieren der generierten Transkriptionen erfolgt unter anderem durch Stenographen. Diese sind durch Ihre besondere Schulung an besonderes Equipment gewöhnt, welches unterstützt werden müssen muss.

==== Laie (Benutzer)

Das Korrigieren der generierten Transkription erfolgt unter anderem durch Laien. Diese benötigen im Gegensatz zu Stenographen eine besonders einfache Bedienung und Hilfen, sodass Sie in einem Live-Kontext mithalten können. Auch die Verwendung _Laien-nahen_ Dateiformaten ist wichtig, wie `.csv`, sodass keine zusätzlichen Hürden entstehen.

==== Externer Videostream (Fremdsystem)

Ein Videostream ohne Untertitlung kann durch das Nutzen unseres Services, schnell und einfach mit Untertiteln versehen werden. Dazu werden einfache/gebräuchliche Schnittstellen benötigen, sodass die Einbindung in unser System einfach möglich ist.

==== Soundslike-Dictionary (Fremdsystem)

Bestimmte Namen und Begriffe sind von KI-Modellen schwer zu erkennen. Diese werden in einem _Soundslike-Dictionary_ gespeichert und können zum Start der Software bereitgestellt werden.

=== Technischer Kontext

image::TechnischerKontext.drawio.svg[]

==== Angular (Fremdsystem)

Für die Entwicklung der Korrektur-Oberfläche, wird das Framework _Angular_ verwendet. Dieses Framework ist weit verbreitet und bietet deshalb genügend Dokumentation und Tutorials, sodass ein schneller Einstieg in die Technologie möglich ist. Da Angular Teil des Node.js Frameworks ist, kann auf viele JavaScript- und TypeScript-Bibliotheken zurückgegriffen werden, welche die Entwicklung vereinfachen. 

==== ASP.NET Core (Fremdsystem)

Für die Entwicklung des Backends, welcher als Schnittstelle zwischen der Korrektur-Oberfläche und den Fremdsystemen dient, wird das Framework _ASP.NET Core_ verwendet. Dieses Framework ist weit verbreitet und bietet deshalb genügend Dokumentation und Tutorials, sodass ein schneller Einstieg in die Technologie möglich ist. Außerdem bieten die zahlreichen nuGet-Packages eine einfache Möglichkeit, um auf Bibliotheken zurückzugreifen, welche die Entwicklung vereinfachen.

==== REST (Fremdsystem)

Um eine einfache Kommunikation zwischen der Korrektur-Oberfläche zum Backend zu ermöglichen, wird das _REST_-Paradigma verwendet. Es handelt sich um ein weit verbreitetes Paradigma und stellt in ASP.NET den quasi-Standard dar.

==== SignalR (Fremdsystem)

Um eine Echtzeit-Kommunikation zwischen der Korrektur-Oberfläche und dem Backend zu ermöglichen, wird das nuGet-Package _SignalR_ verwendet. Somit lassen sich Daten vom Backend aus, in das Frontend streamen. Mit _SignalR_ werden Fallstricke wie die Skalierbarkeit umgangen, die bei klassischen Ansätzen (zB WebSockets) auftreten.

==== WebSocket (Fremdsystem)

Damit unser Service nach außen möglichst breit genutzt werden kann, wird das _WebSocket_-Protokoll verwendet. Dieses Protokoll ist weit verbreitet und wird von vielen Systemen unterstützt. Es ermöglicht eine bidirektionale Kommunikation zwischen Client und Server, welche für die Echtzeit-Kommunikation benötigt wird.

==== Speechmatics (Fremdsystem)

Um eine KI-gestützte Transkription zu ermöglichen, wird die das Tool _Speechmatics_ verwendet. Über einen WebSocket wird die Audiospur an _Speechmatics_ gesendet, welche dann die Transkription zurücksendet. Zusätzlich kann beim Verbindungsaufbau ein _Soundslike-Dictionary_ übergeben werden, welches die Transkription verbessern kann.

==== Untertitelformat WebVTT/vtt und SubRip/srt (Fremdsystem)

Unterschiedliche Videostream-Systeme benötigen, abhängig von Anwendungsfall unterschiedliche Untertitelformate. Die zwei gängigsten Formate sind _WebVTT_ und _SRT_. _WebVTT_ ist das modernere Format, welche zum Beispiel Features wie Textformatierung unterstützt. _SRT_ ist das ältere Format, welches von vielen Systemen noch verwendet wird. Beide Formate müssen von unserem System unterstützt werden.

==== JSON/CSV (Fremdsystem)

Um das _Soundslike-Dictionary_ Importieren und Exportieren zu können, werden Dateiformate benötigt. Besonders verbreitet sind `.json` und `.csv`. Außerdem ist es wichtig, dass auch Tabellen-Formate unterstützt werden, da die Anwender daran gewöhnt sind. Diese Formate müssen von unserem System unterstützt werden.

=== Handschalter / Fußschalter (Fremdsystem)

Um das Bearbeiten komfortabler zu machen und den Korrekturprozess zu beschleunigen, müssen Hand- und/oder Fußschalter von unserem System unterstützt werden. An diese Geräte sind Stenographen gewöhnt und erwarten, dass diese verwendet werden können.
