:imagesdir: ./img
== Bausteinsicht

=== Kontextabgrenzung

.Kontextabgrenzung von Subletic zu anderen Systemen 
image::FachlicherKontext.drawio.svg[Static,80%,align="center"]

Subletic interagiert wie im Kapitel Kontextabgrenzung beschrieben, mit zwei Verschiedenen Fremdsystemen und einem Nutzer:

1. Der Client möchte für einen Videostream eine Untertitelung erhalten und sendet dazu einen Audiostream an Subletic.
2. Eine Speech-Engine wird benötigt, welche den Audiostream in Text umwandelt. 
3. Es wird eine Schnittstelle zur korrigierenden Person benötigt.

Für die Interaktion mit den beiden Fremdsystemen wird ein Backend benötigt, welches die Kommunikation mit diesen übernimmt. Für die Interaktion mit der korrigierenden Person wird ein Frontend benötigt, welches die Schnittstelle zum Nutzer darstellt. Das Frontend soll dem Nutzer die Möglichkeit geben, die Transkription zu korrigeren, den Audiostream zu hören und Unterstützt die Korrektur auf verschiedene Arten.

=== Ebene 1 - Komponenten-Sicht

Mit der Komponenten-Sicht werden die Teilbereiche beider Systeme transparent gemacht. Neben den API-Bereichen die für die Kommunikation mit den Fremdsystemen benötigt werden, tauchen die Domänen: Audio, SpeechBubble und Configuration in Backend und Frontend auf. Sie stellen die Grundpfeiler unserer Software-Architektur dar.

==== Backend

.Domänen-Sicht des Backends
image::Bausteinsicht_1_Backend.drawio.svg[Static,80%,align="center"]

Unser ASP.NET-Backend besteht aus vier Komponenten. Die _Client-Communication_-API kapselt die Kommunikation mit unserem Clienten. Sie empfängt den eingehenden Audiostream und überträgt den fertigen Untertitel zurück. Die _Audio_-Domäne erhält von der _Client-Communication_-API den Audio-Stream und leitet diesen direkt weiter an unsere Speech-Engine. Diese antwortet mit einer Transkription, welche später als Untertitel dient. Die rohe Transkription wird anschließend an die _SpeechBubble_-Domäne weitergeleitet, wo sie zur internen _SpeechBubble_-Datenstruktur übersetzt wird. Diese stellt eine früher Version der Untertitel dar, welche benötigt wird um Teile des Untertitels zu korrigieren. Nach Ablauf einer bestimmten, einstellbaren Zeit, werden einzelne _SpeechBubbles_ zu einem echten Untertitel umgewandelt und mit Hilfe der _Client-Communication_-API an den Clienten ausgeliefert. 

Dieser Kreislauf läuft autonom ab, kann jedoch durch die korrigierende Person bei Bedarf ergänzt werden. Dazu wird die _Frontend-Communication_-API benötigt, welche die Kommunikation mit dem Frontend übernimmt. Zunächst wird diese durch die _Audio_-Domäne dafür genutzt den Audio-Stream an das Frontend weiter zu leiten, sodass dieser gehört werden kann. Außerdem wird die _Frontend-Communication_-API genutzt um neue SpeechBubbles an das Frontend zu senden, um korrigierte SpeechBubbles zu empfangen und über das Ableben von SpeechBubbles zu informieren.

==== Frontend

.Domänen-Sicht des Frontends
image::Bausteinsicht_1_Frontend.drawio.svg[Static,80%,align="center"]

Unser Angular-Frontend besteht aus vier Komponenten. Analog zum Backend, wird die _Backend-Communication_-API genutzt um Daten zum Backend zu Senden oder entgegenzunehmen. Der empfangene Audio-Stream wird innerhalb der _Audio_-Domäne verarbeitet, modifiziert und für die korrigierenden Person abgespielt. Gleiches gilt für die empfangenen SpeechBubbles. Diese werden entgegengenommen und an die _SpeechBubble_-Domäne weitergeleitet. Stößt die korrigierende Person die Bearbeitung einer SpeechBubbles an, wird sie über den selben Weg an das Backend zurückgesendet. Wird ein Sprung in der Position des Audio-Streams (und daraus resultierend die Position des Cursors) ausgelöst, wird dies an die _Audio_-Domäne und die _SpeechBubble_-Domäne kommuniziert.

Isoliert davon wird die _Configuration_-Domäne genutzt, die Konfiguration der Software beim Start des Korrektur-Prozesses an alle betreffenden Komponenten und Fremdsysteme zu kommunizieren. So kann Initial ein _Soundslike-Dictionary_ als Tabellen-Datei übergeben und bearbeitet werden, um der _SpeechEngine_ bei der Erkennung schwieriger Wörter zu helfen. Außerdem werden _Initiale Parameter_, wie die Länge des Zeitintervalls in der eine Sprechblase existiert, hier übergeben. Die gebündelte Start-Konfiguration wird mit Hilfe der _Backend-Communication_-API an das Backend gesendet und damit die Software, beziehungsweise der Korrektur-Prozess gestartet.

=== Ebene 2 - Modul-Sicht

==== Backend

.Modul-Sicht des Backends
image::Bausteinsicht_2_Backend.drawio.svg[Static,80%,align="center"]

==== Frontend

.Modul-Sicht des Frontends
image::Bausteinsicht_2_Frontend.drawio.svg[Static,80%,align="center"]