<<<

== Auslieferungssicht

Diese Sicht beschreibt den Betrieb von Subletic. Es werden die Deployment- und Betriebsartefakte beschrieben, die für den Betrieb von Subletic benötigt werden.

.Reservierte Ports aller Systeme
[options="header", content="center" cols="^,^,^"]
|===
| | Container Port | Innerer Port
s| Backend HTTP 2+| 40114
s| Backend HTTPS 2+| 40115
s| Frontend HTTP | 40110 | 80
s| Frontend HTTPS 2+| 40111
|===

=== Deployment

Beide Repositories stellen ein `Dockerfile.yml` bereit, welche genutzt werden um einen Container zu bauen. Diese können anschließend auf einem Deployment-Server gezogen werden. Anschießend können mit einer `docker-compose.yml` beide Anwendung als mit einander kommunizierende Container gestartet werden. Wichtig ist dabei im Backend folgende Umgebungsvariablen zu setzten:

* SPEECHMATICS_API_KEY
* FRONTEND_URL

Im Frontend muss bei geändertem Deployment-Server die `src/environments/environment.prod.ts` angepasst werden. Hier muss die Variable BACKEND_URL auf die URL des Deployment-Servers zeigen. Nun kann ein _Client_ das Backend erreichen, wie im Folgenden beschrieben wird.

=== Client

Möchte sich ein _Client_ verbinden kann er dies über die den Port: 40114 tun. Der Endpunkt für das Erstellen eines Untertitels mit _Subletic_ ist erreichbar unter:

----
http://URL_des_Deployment-Servers/transcribe:40114
----

Vor dem Senden der Audio-Daten ist der _Client_ verpflichtet zunächst eine Message zu schicken, welche das gewünschte Untertitel-Format spezifiziert. Möglich ist `webvtt` oder `srt`. Wird keine Format-Message geschickt, bricht _Subletic_ die Verbindung ab. Nach Übermittlung des Formats darf begonnen werden Audio-Pakete zu schicken.

=== Browser

_Subletic_ wird mit Chromium basierten Browsern im Hinterkopf entwickelt. Das Funktionieren aller Features wird jedoch nur mit _Google Chrome_ garantiert. Ein Beispiel sind die Hand- und Fußschalter, welche nur mit _Google Chrome_ nutzbar sind. Andere Browser wie _Mozilla Firefox_ werden nicht unterstützt. Wir empfehlen daher die Verwendung von _Google Chrome_. Das Frontend ist erreichbar unter:

----
http://URL_des_Deployment-Servers:40110
----
