:imagesdir: ./img
<<<

== Qualitätsanforderungen

Dieser Abschnitt beinhaltet die geforderten Qualitätsanforderungen und betrachtet einige Qualitätsmerkmale genauer.

=== Qualitätsbaum

.Datenfluss von Subletic
image::QualityTree.drawio.svg[Static,80%,align="center"]

=== Modul-Kopplung

=== Code-Komplexität

=== Testabdeckung

=== 60:30:10-Regel

Die 60:30:10 ist eine Faustregel, mit der im UI-Design die Aufteilung von Farben, Schriftarten und Layouts festgelegt wird. Die 60 steht für die dominierende Farbe, die 30 für die sekundäre und die 10 für die Akzentfarbe. Durch die Orientierung an dieser Farbverteilung wird dem User dabei geholfen sich zu orientieren und der Mental Load wird reduziert. Jedoch sollte beachtet werden dass die 60:30:10-Regel nur eine Faustregel ist und nicht immer eingehalten werden kann und muss. Sie sollte eher als Richtlinie gesehen werden, die bei der Entscheidungsfindung hilft.

=== Audio-Pitch

.Pitch bei normaler Geschwindigkeit
audio::audio/Normal-1x.mp3[]

[options="header", content="center" cols="^,^"]
|===
| Langsamer | Schneller
a| .Pitch bei 0.9x
audio::audio/Langsamer-0_9x.mp3[] 
a| .Pitch bei 1.1x
audio::audio/Schneller-1_1x.mp3[] 
a| .Pitch bei 0.7x
audio::audio/Langsamer-0_7x.mp3[]
a| .Pitch bei 1.3x
audio::audio/Schneller-1_3x.mp3[]
a| .Pitch bei 0.5x
audio::audio/Langsamer-0_5x.mp3[]
a| .Pitch bei 1.5x
audio::audio/Schneller-1_5x.mp3[]
|===

